
kind: Deployment
apiVersion: apps/v1
metadata:
  annotations:
    kubernetes.io/change-cause: "Image version 1.12"
  name: nginx-deployment
  labels:
    project: nginx-php-application

spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  replicas: 3
  selector:
    matchLabels:
      app: nginx
      project: nginx-php-application
  template:
    metadata:
      labels:
        app: nginx
        project: nginx-php-application
    spec:
      containers: 
      - name: nginx-container
        image: nginx:1.12
        ports:
        - containerPort: 80
        volumeMounts:
        - name: website-volume
          mountPath: /usr/share/nginx/html/

        - name: config-volume
          mountPath: /etc/nginx/conf.d/  
      volumes:
      - name: website-volume
        nfs:
          server: 172.31.12.87
          path: /var/website
      - name: config-volume
        configMap:
          name: nginx-config

